### ISSUE TITLE
Recurring job does not start

### ISSUE THREAD

**Issue by TropinAlexey** [bamotav/Hangfire.RecurringJobAdmin#21]
Hi, Bryan.
Thank you for useful extension. I'm trying to use it but it doesn't start through the job configuration panel, although it runs well through "HangfireTaskScheduler" class. Here is what I'm entering to "Add new job" form:

Job Id : AppointmentNotificationJob
Cron : 0 2 * * *
Class : LAPICore.Infrastructure.TaskScheduler.Jobs.AppointmentNotificationJob
Method: Run
Queue: default

Maybe I entered the wrong class path, but I tried to enter different and "LAPICore.Infrastructure.TaskScheduler.Jobs" is that namespace in which this class is located.

What am I doing wrong?
Thank you in advance

**Comment by bamotav** [comment]
Hi @TropinAlexey  this class "LAPICore.Infrastructure.TaskScheduler.Jobs.AppointmentNotificationJob"  you are adding is in a different DLL than the one with the Hangfire package installed?

**Comment by bamotav** [comment]
Hi @TropinAlexey, I replicate this issue and it runs successful, check the next image:

![image](https://user-images.githubusercontent.com/36558623/91122601-ba037f00-e668-11ea-860e-48eeb7e0b62a.png)


![image](https://user-images.githubusercontent.com/36558623/91122480-71e45c80-e668-11ea-8d31-da854a589cbc.png)

But I ran manually because when you add the job the first time it runs dependency the "CRON" configuration, for example, your CRON configuration is "0 2 * * *"  the first execution is at 2020-08-25 02:00:00 because it is configured at 02:00 AM to run, right now is not time to run.

![image](https://user-images.githubusercontent.com/36558623/91122782-2d0cf580-e669-11ea-85ed-5f9e74ca68be.png)

![image](https://user-images.githubusercontent.com/36558623/91123156-29c63980-e66a-11ea-9f6b-8f4cfbdd3aa8.png)

**Comment by TropinAlexey** [comment]
Hi, Bryan.
Thank you for your fast answer.
Of course, I ran my job manually for testing. 

> this class "LAPICore.Infrastructure.TaskScheduler.Jobs.AppointmentNotificationJob" you are adding is in a different DLL than the one with the Hangfire package installed?
Yes, this class is in LAPICore.Infrastructure.dll, where Hangfire package installed too. And reference to assembly is configured as in your explanation:
`services.AddHangfire(configuration =>
            {
                var sqlOptions = new SqlServerStorageOptions
                {
                    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                    QueuePollInterval = TimeSpan.Zero,
                    UseRecommendedIsolationLevel = true,
                    UsePageLocksOnDequeue = true,
                    DisableGlobalLocks = true
                };

                configuration.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseSqlServerStorage(ConfigurationExtension.Configuration.GetConnectionString(Constants.DbConnection), sqlOptions)
                .UseRecurringJobAdmin(typeof(Startup).Assembly);
            });`

**Comment by bamotav** [comment]
Hi @TropinAlexey,

It doesn't matter that the reference assembly in UseRecurringJobAdmin is different, unless you are not adding the job through the JobConfiguration panel but using the attribute:

`[RecurringJob("*/2 * * * *", "China Standard Time", "default", RecurringJobId = "Validate-Process")]
    public void ValidateProcess()
    {
        Console.WriteLine("Validate Process");
    }`

In this case, the reference assembly that you pass in the UseRecurringJobAdmin method looks within that assembly for all the methods that have that attribute.

Your problem is that the Job never starts at the time indicated in the CRON? only when you run it manually?

You can create a new clean project and add a method that will print some message to the console and try to replicate the same problem in that project.

**Comment by TropinAlexey** [comment]
> Your problem is that the Job never starts at the time indicated in the CRON? only when you run it manually?
Wow, you're right!. It runs good by cron automatic schedule but doesn't by "Trigger now" button. Although in both cases Hangfire displays "Success" job status.

> Are you check the time zone, could it be that the server that is running your project does not have that time zone installed, on the other hand, you verified if at the time of executing it is failing?
Yes, I've checked and this is not the case

> You can create a new clean project and add a method that will print some message to the console and try to replicate the same problem in that project?
I will and let you know the result

Thank you for your help again, Bryan

**Comment by bamotav** [comment]
You're welcome @TropinAlexey, let me know if it worked for you to close this issue.

**Comment by bamotav** [comment]
Hello @TropinAlexey, when you can please you can check the new updates since it could be that they help to solve your problem, in which case it continues you could reopen this issue.
